name: SBOM Test
on:
  push:
    branches:
      - feat/sbom
jobs:
  generate-sboms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SBOM for scripts
        uses: CycloneDX/cdxgen-action@5668048b6479c5ee557eec3e1766132a4661681f
        with:
          path: ./scripts
          output: ./output/bom-card.xml
          format: xml
          type: files

      - name: Generate SBOM for website
        uses: CycloneDX/cdxgen-action@5668048b6479c5ee557eec3e1766132a4661681f
        with:
          path: ./cornucopia.owasp.org
          output: ./output/bom-website.xml
          format: xml
          type: files

      - name: Generate SBOM for engine
        uses: CycloneDX/cdxgen-action@5668048b6479c5ee557eec3e1766132a4661681f
        with:
          path: ./copi.owasp.org
          output: ./output/bom-engine.xml
          format: xml
          type: files

      - uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: output/*.xml
